### ISSUE TITLE
Support image resizing before upload

### ISSUE THREAD

**Issue by hugows** [Creling/obsidian-image-uploader#1]
Hello,

any way something like this could be done? Maybe depending on Imagemagick on MacOS and Linux.

Because screenshots are huge nowadays and sometimes you only need a quick reference, no need to use 20 mb for this.

Thanks for this plugin, looking forward to test it!

**Comment by Creling** [comment]
Thanks for feedback. The plugin is available in Obsidian now.

> Support image resizing before upload.

Will, I will consider to implement it by JS. :)

**Comment by Creling** [comment]
Done in https://github.com/Creling/obsidian-image-uploader/commit/c37442002f0d7593cd3c7399068369c8f01f77fc .
Now the plugin can resize the image before uploading. :)
