### ISSUE TITLE
Plugin not installable.

### ISSUE THREAD

**Issue by joethei** [Creling/obsidian-image-uploader#11]
Hi @Creling 
We have noticed that the latest release of your plugin cannot be installed currently.

This is due to the release for version 0.3.1 being unavailable.

We will remove this plugin from the community plugins directory if this issue is not fixed within 30 days.

- The Obsidian Team

**Comment by Creling** [comment]
Hi, thank your for reminder, I have released an valid package.

**Comment by coltisa** [comment]
> Hi, thank your for reminder, I have released an valid package.

Hi @Creling, we still can't install this plugin, don't know if the plugin is still have some issue or due to Obsidian's policy

**Comment by Creling** [comment]
Hi, thank your for the feedback, I will check it.

**Comment by Creling** [comment]
Hello, I test this plugin in a new Obsidian vault and it is installable now.

I deleted version 0.3.1 for a typo in manifest.json and uploaded version 0.3.2 instead. However, Obsidian is unable to detect the presence of version 0.3.2 and continues to download the deleted version 0.3.1, resulting in this problem.

**Comment by joethei** [comment]
the mainfest in your repo also needs to be updated.

**Comment by Creling** [comment]
> the mainfest in your repo also needs to be updated.

yep, thank you for your reminder, I just make a commit (https://github.com/Creling/obsidian-image-uploader/commit/f688a9dbbb2222962dcd8969051862cba6e44151) to update the version number.
