### ISSUE TITLE
unsigned upload to cloudinary - guidance needed

### ISSUE THREAD

**Issue by recspert** [Creling/obsidian-image-uploader#12]
I'm trying to configure uploads via [cloudinary api](https://cloudinary.com/documentation/image_upload_api_reference#unsigned_upload_syntax).  I followed instructions in another plugin to enable unsigned uploads as described [here](https://jordanhandy.github.io/obsidian-cloudinary-uploader/configuring-cloudinary/).

Now, I'm trying to configure the plugin settings. Currently I have:
`Api Endpoint`
```
https://api.cloudinary.com/v1_1/<my_account_name>/image/upload
```

`Upload Header`
```
 (empty)
```

`Upload Body`
```
{
  "file": "$FILE",
  "api_key": "<my_cloudinary_api_key>",
  "upload_preset": "<my_preset_name>"
}
```

When I try to paste an image in an obsidian note the app simply freezes. I have to kill obsidian process.  What should I modify to make the plugin work as expected?

**Comment by Creling** [comment]
Hi, I never heard of cloudinary before. I am now registering a cloudinary account to dig out what happened. :)

**Comment by recspert** [comment]
Thanks a lot!

They have an example on POSTMAN, here's the direct [link](https://postman.com/cloudinaryteam/workspace/programmable-media/folder/16080251-01c1a754-63db-4c3f-9fc7-53cab03d906b?ctx=documentation)

I used their example, and was able to successfully upload an image.


I used the following parameters:
`file`: \<uploaded local file\>
`upload_preset`: \<my upload preset for obisian\>
`api_key`: \<my cloudinary api key\>

And it worked fine. :) I also tried to provide the same info in the `Upload body` field in the plugin, but it still hangs. 

Note, I updated my initial description: removed `timestamp` field, added `api_key` field, as these are the settings that worked for me in the POSTMAN

**Comment by Creling** [comment]
Hey, I find the reason. Please add a `{}` to the `Upload Header` filed, then it will work.

![image](https://github.com/Creling/obsidian-image-uploader/assets/43109504/fd006c67-c530-4a24-ab96-e66664900769)

![image](https://github.com/Creling/obsidian-image-uploader/assets/43109504/ae10da25-3707-46d2-ac3b-b8aebc5bc1b1)

The current version cannot handle null `Upload Header`. I will fix it in the next version.

Thank you for your feedback. :)

**Comment by Creling** [comment]
BTW, this is my upload_preset setting:

![image](https://github.com/Creling/obsidian-image-uploader/assets/43109504/5da8fa8b-290c-4df9-b9c7-2d11039a1ea5)

And this is my obsidian-image-uploader setting:

![image](https://github.com/Creling/obsidian-image-uploader/assets/43109504/6cfcf2d1-eb60-4ecf-87e4-3f554a19ff19)

I will disable this upload_preset several hours later for security reasons.

**Comment by recspert** [comment]
Wow! That was quick! :) It works! Thanks a lot!

I had similar settings for the unsigned upload. Thanks for confirming!

**Comment by Creling** [comment]
LoL, have a nice day. I will close this issue.
