### ISSUE TITLE
你好，可以更新下插件吗。

### ISSUE THREAD

**Issue by wujita01** [Creling/obsidian-image-uploader#4]
我使用你的插件，粘贴图片不会自动上传。obsidian版本 0.15.6。麻烦更新下，谢谢

**Comment by cs-mshah** [comment]
yes, pasting a picture does not get it uploaded.

**Comment by Creling** [comment]
Hey, thank you for your attention to this plugin. @wujita01 @cs-mshah .
I have uploaded a new version and it should work now.
